//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonCode.ICSharpTextEditor {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyntaxFiles {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyntaxFiles() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonCode.ICSharpTextEditor.SyntaxFiles", typeof(SyntaxFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of ActionScript.xshd.
        /// </summary>
        internal static string ActionScript {
            get {
                return ResourceManager.GetString("ActionScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Ada.xshd.
        /// </summary>
        internal static string Ada {
            get {
                return ResourceManager.GetString("Ada", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of ANTLR.xshd.
        /// </summary>
        internal static string ANTLR {
            get {
                return ResourceManager.GetString("ANTLR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Assembly.xshd.
        /// </summary>
        internal static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of AutoHotkey.xshd.
        /// </summary>
        internal static string AutoHotkey {
            get {
                return ResourceManager.GetString("AutoHotkey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Batch.xshd.
        /// </summary>
        internal static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Boo.xshd.
        /// </summary>
        internal static string Boo {
            get {
                return ResourceManager.GetString("Boo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of C.xshd.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Ceylon.xshd.
        /// </summary>
        internal static string Ceylon {
            get {
                return ResourceManager.GetString("Ceylon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of ChucK.xshd.
        /// </summary>
        internal static string ChucK {
            get {
                return ResourceManager.GetString("ChucK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Clojure.xshd.
        /// </summary>
        internal static string Clojure {
            get {
                return ResourceManager.GetString("Clojure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Cocoa.xshd.
        /// </summary>
        internal static string Cocoa {
            get {
                return ResourceManager.GetString("Cocoa", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of CoffeeScript.xshd.
        /// </summary>
        internal static string CoffeeScript {
            get {
                return ResourceManager.GetString("CoffeeScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Cool.xshd.
        /// </summary>
        internal static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of C++.xshd.
        /// </summary>
        internal static string CPlusPlus {
            get {
                return ResourceManager.GetString("CPlusPlus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of CSharp.xshd.
        /// </summary>
        internal static string CSharp {
            get {
                return ResourceManager.GetString("CSharp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of CSS.xshd.
        /// </summary>
        internal static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of D.xshd.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Dart.xshd.
        /// </summary>
        internal static string Dart {
            get {
                return ResourceManager.GetString("Dart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Delphi.xshd.
        /// </summary>
        internal static string Delphi {
            get {
                return ResourceManager.GetString("Delphi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Eiffel.xshd.
        /// </summary>
        internal static string Eiffel {
            get {
                return ResourceManager.GetString("Eiffel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Elixir.xshd.
        /// </summary>
        internal static string Elixir {
            get {
                return ResourceManager.GetString("Elixir", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Erlang.xshd.
        /// </summary>
        internal static string Erlang {
            get {
                return ResourceManager.GetString("Erlang", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of F#.xshd.
        /// </summary>
        internal static string FSharp {
            get {
                return ResourceManager.GetString("FSharp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Falcon.xshd.
        /// </summary>
        internal static string Falcon {
            get {
                return ResourceManager.GetString("Falcon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Fantom.xshd.
        /// </summary>
        internal static string Fantom {
            get {
                return ResourceManager.GetString("Fantom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Fortran95.xshd.
        /// </summary>
        internal static string Fortran95 {
            get {
                return ResourceManager.GetString("Fortran95", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Go.xshd.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Goovy.xshd.
        /// </summary>
        internal static string Goovy {
            get {
                return ResourceManager.GetString("Goovy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Gui4Cli.xshd.
        /// </summary>
        internal static string Gui4Cli {
            get {
                return ResourceManager.GetString("Gui4Cli", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Haskell.xshd.
        /// </summary>
        internal static string Haskell {
            get {
                return ResourceManager.GetString("Haskell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Haxe.xshd.
        /// </summary>
        internal static string Haxe {
            get {
                return ResourceManager.GetString("Haxe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of HTML.xshd.
        /// </summary>
        internal static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Icon.xshd.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of ILYC.xshd.
        /// </summary>
        internal static string ILYC {
            get {
                return ResourceManager.GetString("ILYC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of INI.xshd.
        /// </summary>
        internal static string INI {
            get {
                return ResourceManager.GetString("INI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Io.xshd.
        /// </summary>
        internal static string Io {
            get {
                return ResourceManager.GetString("Io", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Java.xshd.
        /// </summary>
        internal static string Java {
            get {
                return ResourceManager.GetString("Java", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of JavaScript.xshd.
        /// </summary>
        internal static string JavaScript {
            get {
                return ResourceManager.GetString("JavaScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of JSON.xshd.
        /// </summary>
        internal static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Julia.xshd.
        /// </summary>
        internal static string Julia {
            get {
                return ResourceManager.GetString("Julia", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Just BASIC.xshd.
        /// </summary>
        internal static string JustBASIC {
            get {
                return ResourceManager.GetString("JustBASIC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of KiXtart.xshd.
        /// </summary>
        internal static string KiXtart {
            get {
                return ResourceManager.GetString("KiXtart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Kotlin.xshd.
        /// </summary>
        internal static string Kotlin {
            get {
                return ResourceManager.GetString("Kotlin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Lean.xshd.
        /// </summary>
        internal static string Lean {
            get {
                return ResourceManager.GetString("Lean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Lisp.xshd.
        /// </summary>
        internal static string Lisp {
            get {
                return ResourceManager.GetString("Lisp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Lua.xshd.
        /// </summary>
        internal static string Lua {
            get {
                return ResourceManager.GetString("Lua", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of MySQL.xshd.
        /// </summary>
        internal static string MySQL {
            get {
                return ResourceManager.GetString("MySQL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Nemerle.xshd.
        /// </summary>
        internal static string Nemerle {
            get {
                return ResourceManager.GetString("Nemerle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Nim.xshd.
        /// </summary>
        internal static string Nim {
            get {
                return ResourceManager.GetString("Nim", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Objective-C.xshd.
        /// </summary>
        internal static string ObjectiveC {
            get {
                return ResourceManager.GetString("ObjectiveC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of OCaml.xshd.
        /// </summary>
        internal static string OCaml {
            get {
                return ResourceManager.GetString("OCaml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of ParaSail.xshd.
        /// </summary>
        internal static string ParaSail {
            get {
                return ResourceManager.GetString("ParaSail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Pascal.xshd.
        /// </summary>
        internal static string Pascal {
            get {
                return ResourceManager.GetString("Pascal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of PHP.xshd.
        /// </summary>
        internal static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Pike.xshd.
        /// </summary>
        internal static string Pike {
            get {
                return ResourceManager.GetString("Pike", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of PowerShell.xshd.
        /// </summary>
        internal static string PowerShell {
            get {
                return ResourceManager.GetString("PowerShell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Prolog.xshd.
        /// </summary>
        internal static string Prolog {
            get {
                return ResourceManager.GetString("Prolog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of PureScript.xshd.
        /// </summary>
        internal static string PureScript {
            get {
                return ResourceManager.GetString("PureScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Python.xshd.
        /// </summary>
        internal static string Python {
            get {
                return ResourceManager.GetString("Python", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of R.xshd.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Registry.xshd.
        /// </summary>
        internal static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Resource.xshd.
        /// </summary>
        internal static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Rexx.xshd.
        /// </summary>
        internal static string Rexx {
            get {
                return ResourceManager.GetString("Rexx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Rust.xshd.
        /// </summary>
        internal static string Rust {
            get {
                return ResourceManager.GetString("Rust", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Scala.xshd.
        /// </summary>
        internal static string Scala {
            get {
                return ResourceManager.GetString("Scala", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Scheme.xshd.
        /// </summary>
        internal static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Solidity.xshd.
        /// </summary>
        internal static string Solidity {
            get {
                return ResourceManager.GetString("Solidity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Spike.xshd.
        /// </summary>
        internal static string Spike {
            get {
                return ResourceManager.GetString("Spike", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of SQF.xshd.
        /// </summary>
        internal static string SQF {
            get {
                return ResourceManager.GetString("SQF", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Swift.xshd.
        /// </summary>
        internal static string Swift {
            get {
                return ResourceManager.GetString("Swift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of TCL.xshd.
        /// </summary>
        internal static string TCL {
            get {
                return ResourceManager.GetString("TCL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Thrift.xshd.
        /// </summary>
        internal static string Thrift {
            get {
                return ResourceManager.GetString("Thrift", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of T-SQL.xshd.
        /// </summary>
        internal static string TSQL {
            get {
                return ResourceManager.GetString("TSQL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of TypeScript.xshd.
        /// </summary>
        internal static string TypeScript {
            get {
                return ResourceManager.GetString("TypeScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Vala.xshd.
        /// </summary>
        internal static string Vala {
            get {
                return ResourceManager.GetString("Vala", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of VBNET.xshd.
        /// </summary>
        internal static string VBNET {
            get {
                return ResourceManager.GetString("VBNET", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of VBScript.xshd.
        /// </summary>
        internal static string VBScript {
            get {
                return ResourceManager.GetString("VBScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Verilog.xshd.
        /// </summary>
        internal static string Verilog {
            get {
                return ResourceManager.GetString("Verilog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of VHDL.xshd.
        /// </summary>
        internal static string VHDL {
            get {
                return ResourceManager.GetString("VHDL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Volt.xshd.
        /// </summary>
        internal static string Volt {
            get {
                return ResourceManager.GetString("Volt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of VS Solution.xshd.
        /// </summary>
        internal static string VSSolution {
            get {
                return ResourceManager.GetString("VSSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of X10.xshd.
        /// </summary>
        internal static string X10 {
            get {
                return ResourceManager.GetString("X10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of XC.xshd.
        /// </summary>
        internal static string XC {
            get {
                return ResourceManager.GetString("XC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of XML.xshd.
        /// </summary>
        internal static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the content of Xtend.xshd.
        /// </summary>
        internal static string Xtend {
            get {
                return ResourceManager.GetString("Xtend", resourceCulture);
            }
        }
    }
}
